import { Story, Meta } from "@storybook/react";

import AnswersComp, { AnswersCompProps } from ".";

const answersdata = {
  items: [
    {
      comments: [
        {
          owner: {
            reputation: 31279,
            user_id: 30568,
            user_type: "registered",
            accept_rate: 50,
            profile_image:
              "https://www.gravatar.com/avatar/267ff7ac97d2830d7f821b3a58ec4a40?s=128&d=identicon&r=PG",
            display_name: "mghie",
            link: "https://stackoverflow.com/users/30568/mghie",
          },
          edited: false,
          score: 0,
          creation_date: 1267267021,
          post_id: 2345496,
          comment_id: 2319550,
          content_license: "CC BY-SA 2.5",
        },
        {
          owner: {
            reputation: 140064,
            user_id: 874188,
            user_type: "registered",
            accept_rate: 62,
            profile_image: "https://i.stack.imgur.com/ZcY77.png?s=128&g=1",
            display_name: "tripleee",
            link: "https://stackoverflow.com/users/874188/tripleee",
          },
          edited: false,
          score: 0,
          creation_date: 1561036016,
          post_id: 2345496,
          comment_id: 99938857,
          content_license: "CC BY-SA 4.0",
        },
      ],
      owner: { user_type: "does_not_exist", display_name: "user282427" },
      is_accepted: false,
      score: 1,
      last_activity_date: 1267226468,
      creation_date: 1267226468,
      answer_id: 2345496,
      question_id: 2315906,
      content_license: "CC BY-SA 2.5",
      body:
        '<p><a href="http://opensoft.homeip.net/fpgui/" rel="nofollow noreferrer">fpGUI Toolkit</a> is an example of what you want. The latest fpGUI code in the source code repository is based on a multi-windowed design. That simple means every widget/component has a window handle, but Windows or Linux does nothing with that window, other that basic notification messages (mouseenter, mouseexit, etc). fpGUI still has full control over where each component goes, if they are focusable, how they look etc. Some widgets/components in fpGUI are non-windowed components too. eg: TfpgScrollbar, TfpgMainMenu, the button in a ComboBox etc.</p>\n\n<p>If you want a true non-windowed version, mean there is only one top-level window that has a window handle, all other widgets/components inside that window doesn\'t actually exist to the OS (they have no window handles), then fpGUI can help too. The initial design of fpGUI Toolkit was based on such a design. Again, look in the source code repository for the v0.4 branch of code. I that design, fpGUI had to handle absolutely everything, creating mouseenter/mouseleave events, translate co-ordinate systems for container components, handle (fake) component focus states etc... Yes the initial design is a LOT of work, but then you have a very portable framework which can easily be applied to other OSes too.</p>\n\n<p>And yes, fpGUI is fully implemented in the Object Pascal language using the Free Pascal compiler to give me cross-platform support. Currently fpGUI runs on Windows, Linux (32 &amp; 64-bit), Windows Mobile and Embedded Linux (ARM) devices.</p>\n',
    },
    {
      comments: [
        {
          owner: {
            reputation: 221156,
            user_id: 12597,
            user_type: "registered",
            accept_rate: 76,
            profile_image:
              "https://www.gravatar.com/avatar/4b534325156758d6592fb624d7b60e22?s=128&d=identicon&r=PG",
            display_name: "Ian Boyd",
            link: "https://stackoverflow.com/users/12597/ian-boyd",
          },
          edited: false,
          score: 0,
          creation_date: 1267022153,
          post_id: 2324118,
          comment_id: 2296246,
          content_license: "CC BY-SA 2.5",
        },
        {
          owner: {
            reputation: 140064,
            user_id: 874188,
            user_type: "registered",
            accept_rate: 62,
            profile_image: "https://i.stack.imgur.com/ZcY77.png?s=128&g=1",
            display_name: "tripleee",
            link: "https://stackoverflow.com/users/874188/tripleee",
          },
          edited: false,
          score: 0,
          creation_date: 1561036093,
          post_id: 2324118,
          comment_id: 99938908,
          content_license: "CC BY-SA 4.0",
        },
      ],
      owner: {
        reputation: 4668,
        user_id: 45951,
        user_type: "registered",
        accept_rate: 55,
        profile_image:
          "https://www.gravatar.com/avatar/330cc931f797c6b0d0d95e144612aaae?s=128&d=identicon&r=PG",
        display_name: "Yogi Yang 007",
        link: "https://stackoverflow.com/users/45951/yogi-yang-007",
      },
      is_accepted: false,
      score: 0,
      last_activity_date: 1266993084,
      creation_date: 1266993084,
      answer_id: 2324118,
      question_id: 2315906,
      content_license: "CC BY-SA 2.5",
      body:
        '<p>I think <a href="http://opensoft.homeip.net/fpgui/" rel="nofollow noreferrer">fgGUI</a> may help you out.</p>\n\n<p>Do check its <a href="http://en.wikipedia.org/wiki/FpGUI" rel="nofollow noreferrer">Wiki</a> first.</p>\n\n<p>I think you can use this framework for your application in Delphi as it is written totally in Pascal. Actually it is based on FreePascal ;)</p>\n\n<p>HTH</p>\n',
    },
    {
      comments: [
        {
          owner: {
            reputation: 12271,
            user_id: 11956,
            user_type: "registered",
            accept_rate: 67,
            profile_image:
              "https://www.gravatar.com/avatar/545b1236d68c50702e2559640d1c04ed?s=128&d=identicon&r=PG",
            display_name: "Vegar",
            link: "https://stackoverflow.com/users/11956/vegar",
          },
          edited: false,
          score: 0,
          creation_date: 1266955005,
          post_id: 2320126,
          comment_id: 2289982,
          content_license: "CC BY-SA 2.5",
        },
      ],
      owner: {
        reputation: 14916,
        user_id: 9217,
        user_type: "registered",
        accept_rate: 89,
        profile_image: "https://graph.facebook.com/1059830545/picture?type=large",
        display_name: "skamradt",
        link: "https://stackoverflow.com/users/9217/skamradt",
      },
      is_accepted: false,
      score: 1,
      last_activity_date: 1266944911,
      creation_date: 1266944911,
      answer_id: 2320126,
      question_id: 2315906,
      content_license: "CC BY-SA 2.5",
      body:
        "<p>Most of these programs were most likely not originally developed using  RAD type tools so had no choice but to re-invent the wheel.  One of the largest advantages of Delphi is the deep VCL and 3rd party component support to provide the look you desire.  </p>\n\n<p>One technique that I have used with great success to reduce the amount of window handles used in a complex (tax preparation) form based application was to draw the text on a canvas, and moved a single TCustomEdit decendant to the position the user was editing.  It was trivial to capture the TAB/Up/Down keys and move the edit to the appropriate position.  The challenge we discovered was in drawing a hot rectangle around the mouse hovered field.  We ended up with a grid array of TObject, where the array element would be nil (no field), a TLIst (grid contains multiple fields) or a a class that contained our field descriptor.  This reduced the amount of range checks we had to perform since it was more likely that the box only contained a single field, or at most 4 fields.</p>\n",
    },
    {
      comments: [
        {
          owner: {
            reputation: 221156,
            user_id: 12597,
            user_type: "registered",
            accept_rate: 76,
            profile_image:
              "https://www.gravatar.com/avatar/4b534325156758d6592fb624d7b60e22?s=128&d=identicon&r=PG",
            display_name: "Ian Boyd",
            link: "https://stackoverflow.com/users/12597/ian-boyd",
          },
          edited: false,
          score: 0,
          creation_date: 1266943634,
          post_id: 2319497,
          comment_id: 2288295,
          content_license: "CC BY-SA 2.5",
        },
        {
          owner: {
            reputation: 221156,
            user_id: 12597,
            user_type: "registered",
            accept_rate: 76,
            profile_image:
              "https://www.gravatar.com/avatar/4b534325156758d6592fb624d7b60e22?s=128&d=identicon&r=PG",
            display_name: "Ian Boyd",
            link: "https://stackoverflow.com/users/12597/ian-boyd",
          },
          edited: false,
          score: 0,
          creation_date: 1266943701,
          post_id: 2319497,
          comment_id: 2288305,
          content_license: "CC BY-SA 2.5",
        },
        {
          owner: {
            reputation: 221156,
            user_id: 12597,
            user_type: "registered",
            accept_rate: 76,
            profile_image:
              "https://www.gravatar.com/avatar/4b534325156758d6592fb624d7b60e22?s=128&d=identicon&r=PG",
            display_name: "Ian Boyd",
            link: "https://stackoverflow.com/users/12597/ian-boyd",
          },
          edited: false,
          score: 0,
          creation_date: 1266943913,
          post_id: 2319497,
          comment_id: 2288332,
          content_license: "CC BY-SA 2.5",
        },
        {
          owner: {
            reputation: 156581,
            user_id: 33732,
            user_type: "registered",
            accept_rate: 67,
            profile_image:
              "https://www.gravatar.com/avatar/7ea2bfac80ecc1d368ff3a5bb0e58568?s=128&d=identicon&r=PG",
            display_name: "Rob Kennedy",
            link: "https://stackoverflow.com/users/33732/rob-kennedy",
          },
          edited: false,
          score: 0,
          creation_date: 1266947295,
          post_id: 2319497,
          comment_id: 2288799,
          content_license: "CC BY-SA 2.5",
        },
        {
          owner: {
            reputation: 221156,
            user_id: 12597,
            user_type: "registered",
            accept_rate: 76,
            profile_image:
              "https://www.gravatar.com/avatar/4b534325156758d6592fb624d7b60e22?s=128&d=identicon&r=PG",
            display_name: "Ian Boyd",
            link: "https://stackoverflow.com/users/12597/ian-boyd",
          },
          edited: false,
          score: 0,
          creation_date: 1266949023,
          post_id: 2319497,
          comment_id: 2289111,
          content_license: "CC BY-SA 2.5",
        },
        {
          owner: {
            reputation: 156581,
            user_id: 33732,
            user_type: "registered",
            accept_rate: 67,
            profile_image:
              "https://www.gravatar.com/avatar/7ea2bfac80ecc1d368ff3a5bb0e58568?s=128&d=identicon&r=PG",
            display_name: "Rob Kennedy",
            link: "https://stackoverflow.com/users/33732/rob-kennedy",
          },
          edited: false,
          score: 0,
          creation_date: 1266958261,
          post_id: 2319497,
          comment_id: 2290431,
          content_license: "CC BY-SA 2.5",
        },
        {
          owner: {
            reputation: 221156,
            user_id: 12597,
            user_type: "registered",
            accept_rate: 76,
            profile_image:
              "https://www.gravatar.com/avatar/4b534325156758d6592fb624d7b60e22?s=128&d=identicon&r=PG",
            display_name: "Ian Boyd",
            link: "https://stackoverflow.com/users/12597/ian-boyd",
          },
          edited: false,
          score: 0,
          creation_date: 1266981609,
          post_id: 2319497,
          comment_id: 2292714,
          content_license: "CC BY-SA 2.5",
        },
      ],
      owner: {
        reputation: 156581,
        user_id: 33732,
        user_type: "registered",
        accept_rate: 67,
        profile_image:
          "https://www.gravatar.com/avatar/7ea2bfac80ecc1d368ff3a5bb0e58568?s=128&d=identicon&r=PG",
        display_name: "Rob Kennedy",
        link: "https://stackoverflow.com/users/33732/rob-kennedy",
      },
      is_accepted: true,
      score: 4,
      last_activity_date: 1266940195,
      creation_date: 1266940195,
      answer_id: 2319497,
      question_id: 2315906,
      content_license: "CC BY-SA 2.5",
      body:
        "<p>It's futile to build windowless controls <strong>and</strong> fit them into Delphi's VCL framework.</p>\n\n<p>You bring up Internet Explorer as an example. But in that case, it's entirely in charge of everything that resides on it. It has its own internal notion of what the active control is, but think about what it looks like from the outside: It's just one giant control. When you ask the OS what has focus, the single browser control has it, no matter which of the browser's subcontrols <em>appears</em> to have focus.</p>\n\n<p>When you press Tab, it looks to the OS as though the browser has simply consumed a tab character, just like edit controls do. Edit controls move the cursor over a few spaces and add tab characters to their internal buffers; browser controls move the cursor to another region of the display.</p>\n\n<p>You're thinking of doing all this on a Delphi TForm. Delphi forms already have a framework for managing the active control and handling keystrokes, and you're going to have to fight it all. If you want windowless controls, go the Internet Explorer route and <strong>build your own container control</strong> to hold them so that you can remain in charge of everything that happens inside it.</p>\n\n<p>Your container can be a VCL control, but the things you put on it probably can't — they'll still be expecting to use the VCL focus- and keyboard-handling rules. Notice how you can't put ordinary Windows controls in Internet Explorer, either. Anything you put there needs to go through specific ActiveX interfaces. Maybe you'll need interfaces, too, or maybe you can just make your own set of control classes that descend from some special ancestor class you design to work with your container. Don't start with <code>TGraphicControl</code>; it's too entrenched in the VCL to be usable as the basis for your offshoot control library.</p>\n\n<p>It will be a lot of work, but then again, so was Internet Explorer.</p>\n",
    },
    {
      comments: [
        {
          owner: {
            reputation: 221156,
            user_id: 12597,
            user_type: "registered",
            accept_rate: 76,
            profile_image:
              "https://www.gravatar.com/avatar/4b534325156758d6592fb624d7b60e22?s=128&d=identicon&r=PG",
            display_name: "Ian Boyd",
            link: "https://stackoverflow.com/users/12597/ian-boyd",
          },
          edited: false,
          score: 0,
          creation_date: 1266940798,
          post_id: 2318111,
          comment_id: 2287835,
          content_license: "CC BY-SA 2.5",
        },
        {
          owner: {
            reputation: 12271,
            user_id: 11956,
            user_type: "registered",
            accept_rate: 67,
            profile_image:
              "https://www.gravatar.com/avatar/545b1236d68c50702e2559640d1c04ed?s=128&d=identicon&r=PG",
            display_name: "Vegar",
            link: "https://stackoverflow.com/users/11956/vegar",
          },
          edited: false,
          score: 0,
          creation_date: 1266956314,
          post_id: 2318111,
          comment_id: 2290166,
          content_license: "CC BY-SA 2.5",
        },
      ],
      owner: {
        reputation: 12271,
        user_id: 11956,
        user_type: "registered",
        accept_rate: 67,
        profile_image:
          "https://www.gravatar.com/avatar/545b1236d68c50702e2559640d1c04ed?s=128&d=identicon&r=PG",
        display_name: "Vegar",
        link: "https://stackoverflow.com/users/11956/vegar",
      },
      is_accepted: false,
      score: 0,
      last_activity_date: 1266928756,
      creation_date: 1266928756,
      answer_id: 2318111,
      question_id: 2315906,
      content_license: "CC BY-SA 2.5",
      body:
        "<p>I have no idea of what your problem really is, here, but I think this little history may be relevant...</p>\n\n<p>We have an application which fills out a dozen forms. The user may fill out additional forms, and also change values filled out by the application it self.</p>\n\n<p>Now, in our first implementation, we used windowed components for every single input field, so that the fields could receive focus and input. That turned out to be a big problem, because all this windows took a lot of resources.</p>\n\n<p>We now have windowless controls for every input field. That means that all we end up with, is a combined drawing of the form and its input fields. When the user clicks inside the drawing, or uses some keystrokes to move/set focus, we create a new windowed control for the clicked field. When the user moves to the next input field, we destroy the first window, and create a new one. This way we only have one windowed control which again gave us a nice speed improvement.</p>\n\n<p>Again - I have no idea of what you really want to manage. TWinControl is a TWinControl for a reason, but there may be a solution to what you want, what ever that would be...</p>\n",
    },
    {
      comments: [
        {
          owner: {
            reputation: 221156,
            user_id: 12597,
            user_type: "registered",
            accept_rate: 76,
            profile_image:
              "https://www.gravatar.com/avatar/4b534325156758d6592fb624d7b60e22?s=128&d=identicon&r=PG",
            display_name: "Ian Boyd",
            link: "https://stackoverflow.com/users/12597/ian-boyd",
          },
          edited: false,
          score: 0,
          creation_date: 1266940392,
          post_id: 2316494,
          comment_id: 2287739,
          content_license: "CC BY-SA 2.5",
        },
        {
          owner: {
            reputation: 156581,
            user_id: 33732,
            user_type: "registered",
            accept_rate: 67,
            profile_image:
              "https://www.gravatar.com/avatar/7ea2bfac80ecc1d368ff3a5bb0e58568?s=128&d=identicon&r=PG",
            display_name: "Rob Kennedy",
            link: "https://stackoverflow.com/users/33732/rob-kennedy",
          },
          edited: false,
          score: 1,
          creation_date: 1266940608,
          post_id: 2316494,
          comment_id: 2287797,
          content_license: "CC BY-SA 2.5",
        },
        {
          owner: {
            reputation: 221156,
            user_id: 12597,
            user_type: "registered",
            accept_rate: 76,
            profile_image:
              "https://www.gravatar.com/avatar/4b534325156758d6592fb624d7b60e22?s=128&d=identicon&r=PG",
            display_name: "Ian Boyd",
            link: "https://stackoverflow.com/users/12597/ian-boyd",
          },
          reply_to_user: {
            reputation: 156581,
            user_id: 33732,
            user_type: "registered",
            accept_rate: 67,
            profile_image:
              "https://www.gravatar.com/avatar/7ea2bfac80ecc1d368ff3a5bb0e58568?s=128&d=identicon&r=PG",
            display_name: "Rob Kennedy",
            link: "https://stackoverflow.com/users/33732/rob-kennedy",
          },
          edited: false,
          score: 0,
          creation_date: 1266943483,
          post_id: 2316494,
          comment_id: 2288273,
          content_license: "CC BY-SA 2.5",
        },
        {
          owner: {
            reputation: 156581,
            user_id: 33732,
            user_type: "registered",
            accept_rate: 67,
            profile_image:
              "https://www.gravatar.com/avatar/7ea2bfac80ecc1d368ff3a5bb0e58568?s=128&d=identicon&r=PG",
            display_name: "Rob Kennedy",
            link: "https://stackoverflow.com/users/33732/rob-kennedy",
          },
          edited: false,
          score: 0,
          creation_date: 1266947436,
          post_id: 2316494,
          comment_id: 2288823,
          content_license: "CC BY-SA 2.5",
        },
        {
          owner: {
            reputation: 31279,
            user_id: 30568,
            user_type: "registered",
            accept_rate: 50,
            profile_image:
              "https://www.gravatar.com/avatar/267ff7ac97d2830d7f821b3a58ec4a40?s=128&d=identicon&r=PG",
            display_name: "mghie",
            link: "https://stackoverflow.com/users/30568/mghie",
          },
          reply_to_user: {
            reputation: 221156,
            user_id: 12597,
            user_type: "registered",
            accept_rate: 76,
            profile_image:
              "https://www.gravatar.com/avatar/4b534325156758d6592fb624d7b60e22?s=128&d=identicon&r=PG",
            display_name: "Ian Boyd",
            link: "https://stackoverflow.com/users/12597/ian-boyd",
          },
          edited: false,
          score: 0,
          creation_date: 1266949807,
          post_id: 2316494,
          comment_id: 2289232,
          content_license: "CC BY-SA 2.5",
        },
        {
          owner: {
            reputation: 221156,
            user_id: 12597,
            user_type: "registered",
            accept_rate: 76,
            profile_image:
              "https://www.gravatar.com/avatar/4b534325156758d6592fb624d7b60e22?s=128&d=identicon&r=PG",
            display_name: "Ian Boyd",
            link: "https://stackoverflow.com/users/12597/ian-boyd",
          },
          reply_to_user: {
            reputation: 156581,
            user_id: 33732,
            user_type: "registered",
            accept_rate: 67,
            profile_image:
              "https://www.gravatar.com/avatar/7ea2bfac80ecc1d368ff3a5bb0e58568?s=128&d=identicon&r=PG",
            display_name: "Rob Kennedy",
            link: "https://stackoverflow.com/users/33732/rob-kennedy",
          },
          edited: false,
          score: 0,
          creation_date: 1266981720,
          post_id: 2316494,
          comment_id: 2292720,
          content_license: "CC BY-SA 2.5",
        },
      ],
      owner: {
        reputation: 21166,
        user_id: 9842,
        user_type: "registered",
        accept_rate: 88,
        profile_image:
          "https://www.gravatar.com/avatar/5a5fa7f344e2450bf1cb83159517ae3b?s=128&d=identicon&r=PG",
        display_name: "Francesca",
        link: "https://stackoverflow.com/users/9842/francesca",
      },
      is_accepted: false,
      score: 4,
      last_activity_date: 1266911433,
      creation_date: 1266911433,
      answer_id: 2316494,
      question_id: 2315906,
      content_license: "CC BY-SA 2.5",
      body:
        "<p>Yes, it is futile.<br>\nAnd it's not Delphi's fault, you're just fighting Windows itself.<br>\nIf you need a control that behaves like a windowed control, use a windowed one.<br>\nAnd you're right, trying to recreate the whole API stack of windowed controls from scratch is a pain. </p>\n",
    },
    {
      comments: [
        {
          owner: {
            reputation: 221156,
            user_id: 12597,
            user_type: "registered",
            accept_rate: 76,
            profile_image:
              "https://www.gravatar.com/avatar/4b534325156758d6592fb624d7b60e22?s=128&d=identicon&r=PG",
            display_name: "Ian Boyd",
            link: "https://stackoverflow.com/users/12597/ian-boyd",
          },
          edited: false,
          score: 0,
          creation_date: 1266941078,
          post_id: 2315915,
          comment_id: 2287876,
          content_license: "CC BY-SA 2.5",
        },
        {
          owner: {
            reputation: 700470,
            user_id: 20862,
            user_type: "registered",
            accept_rate: 50,
            profile_image:
              "https://www.gravatar.com/avatar/2343ae368d3241278581ce6c87f62a25?s=128&d=identicon&r=PG",
            display_name: "Ignacio Vazquez-Abrams",
            link: "https://stackoverflow.com/users/20862/ignacio-vazquez-abrams",
          },
          edited: false,
          score: 0,
          creation_date: 1266943499,
          post_id: 2315915,
          comment_id: 2288277,
          content_license: "CC BY-SA 2.5",
        },
      ],
      owner: {
        reputation: 700470,
        user_id: 20862,
        user_type: "registered",
        accept_rate: 50,
        profile_image:
          "https://www.gravatar.com/avatar/2343ae368d3241278581ce6c87f62a25?s=128&d=identicon&r=PG",
        display_name: "Ignacio Vazquez-Abrams",
        link: "https://stackoverflow.com/users/20862/ignacio-vazquez-abrams",
      },
      is_accepted: false,
      score: 3,
      last_activity_date: 1266895684,
      creation_date: 1266895684,
      answer_id: 2315915,
      question_id: 2315906,
      content_license: "CC BY-SA 2.5",
      body:
        "<p>Yup, you pretty much have it figured out. Using windowless controls means that you lose everything Windows can do to help you. Having more than a couple on a single actual window is pain.</p>\n",
    },
  ],
  has_more: false,
  quota_max: 300,
  quota_remaining: 255,
};

export default {
  title: "Example/Answers",
  component: AnswersComp,
  excludeStories: ["answersdata"],
} as Meta;

const Template: Story<AnswersCompProps> = (args) => <AnswersComp {...args} />;
export const Default = Template.bind({});
Default.args = {
  answers: answersdata.items,
};
